Repository Hanium2025/msa-server, pull requests merged in 2025-08, with the labels that each got.

#38 [feat #34] 소셜 로그인 구현
  apigateway-service/src/main/java/hanium/apigateway_service/controller/UserController.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/user/response/MemberResponseDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/user/response/NaverConfigResponseDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/CommunityGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/UserGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/security/SecurityConfig.java
  apigateway-service/src/main/java/hanium/apigateway_service/security/filter/JwtAuthenticationFilter.java
  common/src/main/proto/common.proto
  common/src/main/proto/community.proto
  common/src/main/proto/user.proto
  community-service/src/main/java/hanium/community_service/grpc/CommunityGrpcService.java
  user-service/build.gradle
  user-service/src/main/java/hanium/user_service/dto/response/KakaoResponseDTO.java
  user-service/src/main/java/hanium/user_service/dto/response/KakaoUserResponseDTO.java
  user-service/src/main/java/hanium/user_service/dto/response/MemberResponseDTO.java
  user-service/src/main/java/hanium/user_service/dto/response/NaverConfigResponseDTO.java
  user-service/src/main/java/hanium/user_service/dto/response/NaverResponseDTO.java
  user-service/src/main/java/hanium/user_service/dto/response/NaverUserResponseDTO.java
  user-service/src/main/java/hanium/user_service/grpc/UserGrpcService.java
  user-service/src/main/java/hanium/user_service/mapper/MemberGrpcMapper.java
  user-service/src/main/java/hanium/user_service/service/OAuthService.java
  user-service/src/main/java/hanium/user_service/service/impl/OAuthServiceImpl.java
Labels: feature

#45 [feat #22] 메인페이지 API 구현
  .github/PULL_REQUEST_TEMPLATE.md
  apigateway-service/src/main/java/hanium/apigateway_service/config/JwtHandshakeInterceptor.java
  apigateway-service/src/main/java/hanium/apigateway_service/controller/ProductController.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/product/response/ProductMainDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/GrpcChatStreamClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/ProductGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/websocket/ChatWebSocketHandler.java
  common/src/main/java/hanium/common/exception/ErrorCode.java
  common/src/main/proto/product.proto
  product-service/build.gradle
  product-service/src/main/java/hanium/product_service/config/RedisConfig.java
  product-service/src/main/java/hanium/product_service/domain/Category.java
  product-service/src/main/java/hanium/product_service/domain/Message.java
  product-service/src/main/java/hanium/product_service/domain/Product.java
  product-service/src/main/java/hanium/product_service/dto/request/ChatMessageRequestDTO.java
  product-service/src/main/java/hanium/product_service/dto/response/GetMyChatroomResponseDTO.java
  product-service/src/main/java/hanium/product_service/dto/response/ProductMainDTO.java
  product-service/src/main/java/hanium/product_service/grpc/ChatGrpcService.java
  product-service/src/main/java/hanium/product_service/grpc/ChattingGrpcService.java
  product-service/src/main/java/hanium/product_service/grpc/ProductGrpcService.java
  product-service/src/main/java/hanium/product_service/mapper/ProductGrpcMapper.java
  product-service/src/main/java/hanium/product_service/repository/ChatroomRepository.java
  product-service/src/main/java/hanium/product_service/repository/ProductRepository.java
  product-service/src/main/java/hanium/product_service/repository/RecentViewRepository.java
  product-service/src/main/java/hanium/product_service/repository/projection/ProductIdCategory.java
  product-service/src/main/java/hanium/product_service/service/ChatMessageTxService.java
  product-service/src/main/java/hanium/product_service/service/ProductService.java
  product-service/src/main/java/hanium/product_service/service/impl/ChatServiceImpl.java
  product-service/src/main/java/hanium/product_service/service/impl/ProductServiceImpl.java
  product-service/src/test/java/hanium/product_service/service/impl/ProductServiceImplTest.java
  user-service/src/main/java/hanium/user_service/dto/request/GetNicknameRequestDTO.java
  user-service/src/main/java/hanium/user_service/repository/ProfileRepository.java
  user-service/src/main/java/hanium/user_service/service/ProfileService.java
Labels: feature

#47 [chore #46] 상품 등록, 조회 응답 값 및 SMS 인증 메시지 내용 수정
  apigateway-service/src/main/java/hanium/apigateway_service/dto/product/response/ProductResponseDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/security/filter/JwtAuthenticationFilter.java
  common/src/main/proto/product.proto
  product-service/src/main/java/hanium/product_service/domain/Category.java
  product-service/src/main/java/hanium/product_service/dto/request/RegisterProductRequestDTO.java
  product-service/src/main/java/hanium/product_service/dto/response/ProductResponseDTO.java
  product-service/src/main/java/hanium/product_service/mapper/ProductGrpcMapper.java
  product-service/src/main/java/hanium/product_service/service/impl/ProductServiceImpl.java
  product-service/src/test/java/hanium/product_service/service/impl/ProductServiceImplTest.java
  user-service/src/main/java/hanium/user_service/util/CoolSmsUtil.java
Labels: enhancement

#49 [chore #48] 소셜로그인 로그 추가
  user-service/src/main/java/hanium/user_service/service/impl/OAuthServiceImpl.java
Labels: enhancement

#57 [refactor #56] 상품 CRUD 로직 개선, 상품 응답 수정
  apigateway-service/src/main/java/hanium/apigateway_service/dto/product/response/ProductResponseDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/ProductGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/mapper/ProductGrpcMapperForGateway.java
  common/src/main/java/hanium/common/exception/ErrorCode.java
  common/src/main/java/hanium/common/exception/GrpcUtil.java
  common/src/main/proto/product.proto
  common/src/main/proto/user.proto
  product-service/build.gradle
  product-service/src/main/java/hanium/product_service/domain/BaseEntity.java
  product-service/src/main/java/hanium/product_service/domain/Category.java
  product-service/src/main/java/hanium/product_service/domain/Product.java
  product-service/src/main/java/hanium/product_service/domain/ProductLike.java
  product-service/src/main/java/hanium/product_service/dto/request/UpdateProductRequestDTO.java
  product-service/src/main/java/hanium/product_service/dto/response/ProductImageDTO.java
  product-service/src/main/java/hanium/product_service/dto/response/ProductResponseDTO.java
  product-service/src/main/java/hanium/product_service/dto/response/ProfileResponseDTO.java
  product-service/src/main/java/hanium/product_service/elasticsearch/ProductDocument.java
  product-service/src/main/java/hanium/product_service/grpc/ProductGrpcService.java
  product-service/src/main/java/hanium/product_service/grpc/ProfileGrpcClient.java
  product-service/src/main/java/hanium/product_service/mapper/ProductGrpcMapper.java
  product-service/src/main/java/hanium/product_service/repository/ProductReadRepository.java
  product-service/src/main/java/hanium/product_service/repository/ProductRepository.java
  product-service/src/main/java/hanium/product_service/repository/RecentViewRepository.java
  product-service/src/main/java/hanium/product_service/repository/projection/ProductCoreProjection.java
  product-service/src/main/java/hanium/product_service/service/ProductService.java
  product-service/src/main/java/hanium/product_service/service/impl/ProductServiceImpl.java
  product-service/src/test/java/hanium/product_service/service/impl/ProductServiceImplTest.java
  user-service/src/main/java/hanium/user_service/dto/response/ProfileResponseDTO.java
  user-service/src/main/java/hanium/user_service/grpc/UserGrpcService.java
  user-service/src/main/java/hanium/user_service/mapper/MemberGrpcMapper.java
  user-service/src/main/java/hanium/user_service/service/ProfileService.java
  user-service/src/main/java/hanium/user_service/service/impl/AuthServiceImpl.java
  user-service/src/main/java/hanium/user_service/service/impl/ProfileServiceImpl.java
  user-service/src/test/java/hanium/user_service/service/AuthServiceImplTest.java
  user-service/src/test/java/hanium/user_service/service/OAuthServiceImplTest.java
Labels: bug, enhancement

#62 [feat #61] 상품 신고 기능 구현
  apigateway-service/src/main/java/hanium/apigateway_service/controller/ProductController.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/product/request/ReportProductRequestDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/ProductGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/mapper/ProductGrpcMapperForGateway.java
  common/src/main/java/hanium/common/exception/ErrorCode.java
  common/src/main/proto/product.proto
  product-service/src/main/java/hanium/product_service/domain/ProductReport.java
  product-service/src/main/java/hanium/product_service/domain/ReportReason.java
  product-service/src/main/java/hanium/product_service/dto/request/ReportProductRequestDTO.java
  product-service/src/main/java/hanium/product_service/grpc/ProductGrpcService.java
  product-service/src/main/java/hanium/product_service/repository/ProductReportRepository.java
  product-service/src/main/java/hanium/product_service/service/ProductReportService.java
  product-service/src/main/java/hanium/product_service/service/impl/ProductReportServiceImpl.java
  product-service/src/test/java/hanium/product_service/service/impl/ProductReportServiceImplTest.java
Labels: feature

#66 [feat #63, fix #64, refactor # 65] 채팅 기능 수정
  apigateway-service/src/main/java/hanium/apigateway_service/controller/ChatController.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/chat/request/CreateChatroomRequestDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/chat/response/GetMyChatroomResponseDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/ChatroomGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/mapper/ChatGrpcMapperForGateway.java
  common/src/main/proto/chatroom.proto
  product-service/src/main/java/hanium/product_service/domain/Chatroom.java
  product-service/src/main/java/hanium/product_service/dto/response/GetMyChatroomResponseDTO.java
  product-service/src/main/java/hanium/product_service/grpc/ChatGrpcService.java
  product-service/src/main/java/hanium/product_service/grpc/ChattingGrpcService.java
  product-service/src/main/java/hanium/product_service/grpc/ProfileGrpcClient.java
  product-service/src/main/java/hanium/product_service/service/impl/ChatServiceImpl.java
  product-service/src/test/java/hanium/product_service/service/impl/ChatServiceImplTest.java
Labels: enhancement

#67 [feat #35] 상품 검색 기록 조회 및 삭제 구현
  apigateway-service/src/main/java/hanium/apigateway_service/controller/ProductController.java
  apigateway-service/src/main/java/hanium/apigateway_service/dto/product/response/ProductSearchHistoryDTO.java
  apigateway-service/src/main/java/hanium/apigateway_service/grpc/ProductGrpcClient.java
  apigateway-service/src/main/java/hanium/apigateway_service/mapper/ProductGrpcMapperForGateway.java
  common/src/main/java/hanium/common/exception/ErrorCode.java
  common/src/main/proto/product.proto
  product-service/src/main/java/hanium/product_service/dto/response/ProductSearchHistoryDTO.java
  product-service/src/main/java/hanium/product_service/grpc/ProductGrpcService.java
  product-service/src/main/java/hanium/product_service/mapper/ProductGrpcMapper.java
  product-service/src/main/java/hanium/product_service/repository/ProductSearchRepository.java
  product-service/src/main/java/hanium/product_service/service/ProductSearchService.java
  product-service/src/main/java/hanium/product_service/service/impl/ProductSearchServiceImpl.java
Labels: feature
